server:
  controller:
    port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: 
  dbname: distributed_system

redis:
  host: localhost
  port: 6379
  user: default
  password: 

security:
  agent_secret: 
  jwt_secret: 
  agent_signature: 
